default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["PG_USERNAME"] %>
  password: <%= ENV["PG_PASSWORD"] %>
  host: 127.0.0.1


development:
  <<: *default
  database: quimera_ants_development
  port: <%= ENV["PGPORT"] || 5432 %>

test:
  <<: *default
  database: quimera_ants_test
  port: <%= ENV["PGPORT"] || 5432 %>

production:
  primary: &primary_production
    <<: *default
    database: quimera_ants_production
    username: quimera_ants
    password: <%= ENV["QUIMERA_ANTS_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: quimera_ants_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: quimera_ants_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: quimera_ants_production_cable
    migrations_paths: db/cable_migrate
